# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchFlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SearchFlow
    pod 'Alamofire', '~> 5.2'
    pod 'ObjectMapper', '~> 3.5'
    pod 'MJRefresh'
    pod 'SDWebImage', '~> 5.0'
  target 'SearchFlowTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
